//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public Employee()
        {
            this.EmployeeDepartments = new HashSet<EmployeeDepartment>();
        }
    
        public virtual long Id { get; set; }
        public virtual string Name { get; set; }
        public virtual decimal Salary { get; set; }
    
        public ICollection<EmployeeDepartment> EmployeeDepartments { get; set; }
    }
}
